[package]
name = "lms-proto"
version = "0.1.0"
edition = "2024"
description = "A library for building clients to connect to Logitech Media Server (LMS)"
documentation = "https://docs.rs/lms-proto"
readme = "README.md"
homepage = "https://github.com/GeoffClements/lms-player"
repository = "https://github.com/GeoffClements/lms-player"
license = "MIT"

[dependencies]
bitflags = "2.11.1"
bytes = "1.11.1"
mac_address = "1.1.8"